# Base Packages
brew 'ag'
brew 'ansible'
brew 'autojump'
brew 'awscli'
brew 'binutils'
brew 'coreutils'
brew 'curl'
brew 'diff-so-fancy'
brew 'fzf'
brew 'git'
brew 'htop-osx'
brew 'ical-buddy'
brew 'imagemagick'
brew 'jq'
brew 'mosh'
brew 'multimarkdown'
brew 'ncdu'
brew 'neovim'
brew 'nvm'
brew 'parallel'
brew 'pstree'
brew 'rbenv'
brew 'rbenv'
brew 'rbenv-bundle-exec'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'stunnel'
brew 'switchaudio-osx'
brew 'thefuck'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'zsh'
brew 'zsh-completion'

# Cask Mac Apps
cask_args appdir: '/Applications'

cask '1password'
cask '1password-cli'
cask 'alacrity'
cask 'alfred'
cask 'anylist'
cask 'bartender'
cask 'cardhop'
cask 'docker'
cask 'drafts'
cask 'fantastical'
cask 'karabiner-elements'
cask 'java'
cask 'moom'
cask 'omnifocus'
cask 'path-finder'
cask 'paw'
cask 'screens'
cask 'slack'
cask 'spotify'
cask 'switchresx'
cask 'textexpander'
cask 'tower'
cask 'transmit'
cask 'vnc-viewer'
cask 'viscosity'
cask 'xbar'
cask 'xscreensaver'

# Mac App Store stuff
brew 'mas'
mas 'Location Helper for Applescript', id: 488536386
mas 'Soulver', id: 413965349
