---
database_file: /Users/metcalf/.timetrap/timetrap.db
round_in_seconds: 60
append_notes_delimiter: ' '
formatter_search_paths:
- /Users/metcalf/.timetrap/formatters
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- /Users/metcalf/.timetrap/auto_sheets
default_command: display
auto_checkout: false
require_note: false
