# Kanagawa Wave
set -g @theme-bg         "#1f1f28"
set -g @theme-fg         "#dcd7ba"
set -g @theme-dim        "#727169"
set -g @theme-accent     "#7e9cd8"
set -g @theme-accent-alt "#957fb8"
set -g @theme-border     "#54546d"
set -g @theme-wait       "#e82424"
set -g @theme-busy       "#ff9e3b"
set -g @theme-done       "#98bb6c"
set -g @theme-remote     "#7aa89f"
