# Nord
set -g @theme-bg         "#2e3440"
set -g @theme-fg         "#d8dee9"
set -g @theme-dim        "#4c566a"
set -g @theme-accent     "#88c0d0"
set -g @theme-accent-alt "#b48ead"
set -g @theme-border     "#434c5e"
set -g @theme-wait       "#bf616a"
set -g @theme-busy       "#ebcb8b"
set -g @theme-done       "#a3be8c"
set -g @theme-remote     "#81a1c1"
