# Rose Pine
set -g @theme-bg         "#191724"
set -g @theme-fg         "#e0def4"
set -g @theme-dim        "#6e6a86"
set -g @theme-accent     "#c4a7e7"
set -g @theme-accent-alt "#ebbcba"
set -g @theme-border     "#403d52"
set -g @theme-wait       "#eb6f92"
set -g @theme-busy       "#f6c177"
set -g @theme-done       "#31748f"
set -g @theme-remote     "#9ccfd8"
