// Generated by Secure ShellFish — forwards OpenCode events to shellfish-notify.sh.
module.exports = {
  hooks: {
    "session.idle": async (context) => {
      const { spawn } = require("child_process");
      const proc = spawn("/home/krezel/.config/opencode/shellfish-notify.sh", ["opencode"], { stdio: ["pipe", "ignore", "ignore"] });
      proc.stdin.end(JSON.stringify(context || {}));
    },
  },
};