-- tmarchy-theme — follow the theme tmarchy is using.
--
-- The state file is GENERATED by `tmarchy-theme sync` from the same
-- themes/<name>.conf the tmux bar reads, so there is one source of truth and
-- nvim does not need tmux to be running to know the theme.
--
-- Why a name and not a palette: tmarchy's ten semantic colours describe a
-- status bar. A syntax highlighter needs a whole scheme, so the theme file
-- names the real colorscheme instead of trying to synthesise one from ten
-- values. Two of the nine map to Neovim BUILT-INS (matte-black -> quiet,
-- jewel -> retrobox) and so need no plugin at all.
local M = {}

M.FALLBACK = "tokyonight-night"

local function state_file()
  local base = os.getenv("XDG_STATE_HOME")
  if base == nil or base == "" then
    base = (os.getenv("HOME") or "") .. "/.local/state"
  end
  return base .. "/tmarchy/current.lua"
end

-- Returns the state table, or nil on a host that has never run tmarchy. Every
-- failure is soft: a missing or malformed state file must leave the editor
-- usable, not throw during startup.
function M.read()
  local chunk = loadfile(state_file())
  if not chunk then return nil end
  local ok, t = pcall(chunk)
  if ok and type(t) == "table" then return t end
  return nil
end

function M.apply(opts)
  opts = opts or {}
  local state = M.read()
  local name = state and state.nvim or M.FALLBACK

  -- lazy.nvim loads a colorscheme plugin on demand when :colorscheme names one
  -- it provides, so pcall is enough here -- no explicit require("lazy").load.
  local ok = pcall(vim.cmd.colorscheme, name)
  if not ok then
    -- Silently landing on Neovim's default would look like a broken config
    -- rather than a missing plugin, so say which name failed.
    if not opts.quiet then
      vim.notify(
        ("tmarchy: colorscheme %q is unavailable, falling back to %s"):format(name, M.FALLBACK),
        vim.log.levels.WARN
      )
    end
    pcall(vim.cmd.colorscheme, M.FALLBACK)
    return M.FALLBACK, false
  end
  return name, true
end

-- :TmarchyTheme re-reads the state file and repaints, so switching theme in
-- tmux does not require restarting an editor you have buffers open in.
function M.setup()
  vim.api.nvim_create_user_command("TmarchyTheme", function()
    local name = M.apply()
    vim.notify("tmarchy: " .. name)
  end, { desc = "Re-apply the current tmarchy colorscheme" })
end

return M
